import React, { useEffect, useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useBundlesStore } from '../stores/bundles.store';
import { useABTestsStore } from '../stores/ab-tests.store';
import { useAuthenticatedFetch } from '../hooks/useAuthenticatedFetch';
import { BundleTable } from '../components/bundles/BundleTable';
import { LoadingState } from '../components/common/LoadingState';
import { ConfirmDialog } from '../components/common/ConfirmDialog';
import { Button } from '../components/common/Button';
import { useToast } from '../components/common/Toast';
import type { BundleDto } from '@bundlify/shared-types';

const STATUS_FILTERS = [
  { value: 'ALL', label: 'All' },
  { value: 'ACTIVE', label: 'Active' },
  { value: 'DRAFT', label: 'Draft' },
  { value: 'PAUSED', label: 'Paused' },
  { value: 'ARCHIVED', label: 'Archived' },
] as const;

export function Bundles() {
  const fetch = useAuthenticatedFetch();
  const navigate = useNavigate();
  const { showToast } = useToast();
  const {
    bundles,
    loading,
    error,
    fetchBundles,
    deleteBundle,
    setStatus,
    generateBundles,
  } = useBundlesStore();

  const { createTest } = useABTestsStore();

  const [generating, setGenerating] = useState(false);
  const [generateResult, setGenerateResult] = useState<number | null>(null);
  const [abTestBundleId, setAbTestBundleId] = useState<string | null>(null);
  const [abTestVariantPct, setAbTestVariantPct] = useState(10);

  // Search & filter state
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');

  // Delete confirmation
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);

  useEffect(() => {
    fetchBundles(fetch);
  }, []);

  const handleEdit = (bundle: BundleDto) => {
    navigate(`/bundles/${bundle.id}/edit`);
  };

  const handleDelete = async (bundleId: string) => {
    setDeleteTarget(bundleId);
  };

  const confirmDelete = async () => {
    if (!deleteTarget) return;
    await deleteBundle(fetch, deleteTarget);
    showToast('Bundle deleted');
    setDeleteTarget(null);
  };

  const handleStatusChange = async (bundleId: string, status: string) => {
    await setStatus(fetch, bundleId, status);
    showToast(`Bundle ${status.toLowerCase()}`);
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setGenerateResult(null);
    const count = await generateBundles(fetch);
    setGenerateResult(count);
    setGenerating(false);
    if (count > 0) showToast(`${count} bundle${count !== 1 ? 's' : ''} generated`);
  };

  const handleCreateABTest = async () => {
    if (!abTestBundleId) return;
    const bundle = bundles.find((b) => b.id === abTestBundleId);
    if (!bundle) return;
    await createTest(fetch, {
      name: `${bundle.name} - Discount Test`,
      bundleId: abTestBundleId,
      variantDiscountPct: abTestVariantPct,
    });
    setAbTestBundleId(null);
    setAbTestVariantPct(10);
    showToast('A/B test created');
  };

  const autoGeneratedDrafts = bundles.filter(
    (b) => b.source === 'AUTO' && b.status === 'DRAFT',
  );

  // Filtered bundles
  const filteredBundles = useMemo(() => {
    let result = bundles;
    if (statusFilter !== 'ALL') {
      result = result.filter((b) => b.status === statusFilter);
    }
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter(
        (b) =>
          b.name.toLowerCase().includes(q) ||
          b.type.toLowerCase().includes(q),
      );
    }
    return result;
  }, [bundles, statusFilter, searchQuery]);

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '20px' }}>
      {/* Header */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: '20px',
        }}
      >
        <h1 style={{ fontSize: '24px', margin: 0 }}>Bundles</h1>
        <div style={{ display: 'flex', gap: '8px' }}>
          <Button variant="secondary" onClick={handleGenerate} disabled={generating}>
            {generating ? 'Generating...' : 'Generate Bundles'}
          </Button>
          <Button onClick={() => navigate('/bundles/new')}>
            Create Bundle
          </Button>
        </div>
      </div>

      {/* Generate result banner */}
      {generateResult !== null && (
        <div
          style={{
            padding: '12px 16px',
            backgroundColor: generateResult > 0 ? '#f1f8f5' : '#fff8e5',
            border: `1px solid ${generateResult > 0 ? '#aee9d1' : '#ffea8a'}`,
            borderRadius: '8px',
            marginBottom: '16px',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <span style={{ fontSize: '14px' }}>
            {generateResult > 0
              ? `${generateResult} bundle${generateResult !== 1 ? 's' : ''} generated as drafts. Review them below.`
              : 'No new bundles could be generated. Adjust your settings or add more products with COGS data.'}
          </span>
          <button
            onClick={() => setGenerateResult(null)}
            aria-label="Dismiss"
            style={{
              background: 'none',
              border: 'none',
              cursor: 'pointer',
              fontSize: '16px',
              color: '#5c5f62',
            }}
          >
            x
          </button>
        </div>
      )}

      {error && (
        <div
          style={{
            color: '#8c1a1a',
            padding: '12px',
            marginBottom: '12px',
            backgroundColor: '#ffd2d2',
            borderRadius: '8px',
          }}
        >
          Error: {error}
        </div>
      )}

      {loading ? (
        <LoadingState />
      ) : (
        <>
          {/* Auto-generated drafts section */}
          {autoGeneratedDrafts.length > 0 && (
            <div
              style={{
                marginBottom: '24px',
                border: '1px solid #e1e3e5',
                borderRadius: '8px',
                overflow: 'hidden',
              }}
            >
              <div
                style={{
                  padding: '12px 16px',
                  backgroundColor: '#fff8e5',
                  borderBottom: '1px solid #ffea8a',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <div>
                  <strong style={{ fontSize: '14px' }}>
                    Auto-Generated Bundles for Review
                  </strong>
                  <span
                    style={{
                      fontSize: '13px',
                      color: '#5c5f62',
                      marginLeft: '8px',
                    }}
                  >
                    ({autoGeneratedDrafts.length} pending)
                  </span>
                </div>
              </div>
              <div style={{ padding: '0' }}>
                {autoGeneratedDrafts.map((bundle) => (
                  <div
                    key={bundle.id}
                    style={{
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      padding: '10px 16px',
                      borderBottom: '1px solid #f1f1f1',
                    }}
                  >
                    <div>
                      <div style={{ fontWeight: 500, fontSize: '14px' }}>
                        {bundle.name}
                      </div>
                      <div style={{ fontSize: '12px', color: '#5c5f62' }}>
                        {bundle.items.length} items | $
                        {bundle.bundlePrice.toFixed(2)} | {bundle.discountPct}%
                        off
                        {bundle.contributionMarginPct !== null && (
                          <span
                            style={{
                              marginLeft: '8px',
                              color:
                                bundle.contributionMarginPct >= 15
                                  ? '#1a5632'
                                  : '#8c1a1a',
                            }}
                          >
                            Margin: {bundle.contributionMarginPct.toFixed(1)}%
                          </span>
                        )}
                      </div>
                    </div>
                    <div style={{ display: 'flex', gap: '6px' }}>
                      <Button size="sm" onClick={() => handleStatusChange(bundle.id, 'ACTIVE')}>
                        Approve
                      </Button>
                      <Button size="sm" variant="danger" onClick={() => handleStatusChange(bundle.id, 'ARCHIVED')}>
                        Reject
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Search & filter bar */}
          <div style={{
            display: 'flex',
            gap: '8px',
            marginBottom: '12px',
            alignItems: 'center',
            flexWrap: 'wrap',
          }}>
            <input
              type="text"
              placeholder="Search bundles..."
              aria-label="Search bundles"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{
                padding: '6px 12px',
                border: '1px solid #c9cccf',
                borderRadius: '4px',
                fontSize: '14px',
                width: '240px',
                maxWidth: '100%',
              }}
            />
            <div style={{ display: 'flex', gap: '2px' }}>
              {STATUS_FILTERS.map((f) => (
                <button
                  key={f.value}
                  onClick={() => setStatusFilter(f.value)}
                  style={{
                    padding: '5px 12px',
                    fontSize: '12px',
                    fontWeight: statusFilter === f.value ? 600 : 400,
                    color: statusFilter === f.value ? '#008060' : '#5c5f62',
                    backgroundColor: statusFilter === f.value ? '#f1f8f5' : 'transparent',
                    border: statusFilter === f.value ? '1px solid #aee9d1' : '1px solid transparent',
                    borderRadius: '4px',
                    cursor: 'pointer',
                    transition: 'all 0.15s ease',
                  }}
                >
                  {f.label}
                </button>
              ))}
            </div>
            <span style={{ fontSize: '13px', color: '#5c5f62', marginLeft: 'auto' }}>
              {filteredBundles.length} bundle{filteredBundles.length !== 1 ? 's' : ''}
            </span>
          </div>

          <BundleTable
            bundles={filteredBundles}
            onEdit={handleEdit}
            onDelete={handleDelete}
            onStatusChange={handleStatusChange}
            onCreateABTest={(bundleId) => setAbTestBundleId(bundleId)}
          />
        </>
      )}

      {/* Delete confirmation dialog */}
      <ConfirmDialog
        open={!!deleteTarget}
        title="Delete Bundle"
        message="Are you sure you want to delete this bundle? This action cannot be undone."
        confirmLabel="Delete"
        variant="danger"
        onConfirm={confirmDelete}
        onCancel={() => setDeleteTarget(null)}
      />

      {/* A/B Test creation dialog */}
      {abTestBundleId && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Create A/B Test"
          onClick={() => { setAbTestBundleId(null); setAbTestVariantPct(10); }}
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
            animation: 'bundlify-overlay-in 0.15s ease',
          }}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              backgroundColor: '#ffffff',
              borderRadius: '12px',
              width: '480px',
              maxWidth: '90vw',
              padding: '24px',
              boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
              animation: 'bundlify-dialog-in 0.2s ease',
            }}
          >
            <h2 style={{ margin: '0 0 16px 0', fontSize: '18px' }}>
              Create A/B Test
            </h2>
            <div style={{ fontSize: '13px', color: '#5c5f62', marginBottom: '16px' }}>
              Bundle: <strong style={{ color: '#202223' }}>
                {bundles.find((b) => b.id === abTestBundleId)?.name ?? abTestBundleId}
              </strong>
            </div>
            <div style={{ marginBottom: '16px' }}>
              <label style={{ display: 'block', fontSize: '13px', color: '#5c5f62', marginBottom: '4px' }}>
                Variant Discount %
              </label>
              <input
                type="number"
                value={abTestVariantPct}
                onChange={(e) => setAbTestVariantPct(parseFloat(e.target.value) || 0)}
                min={1}
                max={100}
                step={1}
                aria-label="Variant discount percentage"
                style={{
                  width: '100%',
                  padding: '8px 12px',
                  border: '1px solid #c9cccf',
                  borderRadius: '4px',
                  fontSize: '14px',
                  boxSizing: 'border-box',
                }}
              />
              <div style={{ fontSize: '11px', color: '#5c5f62', marginTop: '4px' }}>
                The control uses the current bundle discount. Set the variant discount to test against it.
              </div>
            </div>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px' }}>
              <Button variant="secondary" onClick={() => { setAbTestBundleId(null); setAbTestVariantPct(10); }}>
                Cancel
              </Button>
              <Button onClick={handleCreateABTest}>
                Create Test
              </Button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
