import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useBundlesStore } from '../stores/bundles.store';
import { useABTestsStore } from '../stores/ab-tests.store';
import { useAuthenticatedFetch } from '../hooks/useAuthenticatedFetch';
import { BundleTable } from '../components/bundles/BundleTable';
import { LoadingState } from '../components/common/LoadingState';
import type { BundleDto } from '@bundlify/shared-types';

export function Bundles() {
  const fetch = useAuthenticatedFetch();
  const navigate = useNavigate();
  const {
    bundles,
    loading,
    error,
    fetchBundles,
    deleteBundle,
    setStatus,
    generateBundles,
  } = useBundlesStore();

  const { createTest } = useABTestsStore();

  const [generating, setGenerating] = useState(false);
  const [generateResult, setGenerateResult] = useState<number | null>(null);
  const [abTestBundleId, setAbTestBundleId] = useState<string | null>(null);
  const [abTestVariantPct, setAbTestVariantPct] = useState(10);

  useEffect(() => {
    fetchBundles(fetch);
  }, []);

  const handleEdit = (bundle: BundleDto) => {
    navigate(`/bundles/${bundle.id}/edit`);
  };

  const handleDelete = async (bundleId: string) => {
    if (window.confirm('Are you sure you want to delete this bundle?')) {
      await deleteBundle(fetch, bundleId);
    }
  };

  const handleStatusChange = async (bundleId: string, status: string) => {
    await setStatus(fetch, bundleId, status);
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setGenerateResult(null);
    const count = await generateBundles(fetch);
    setGenerateResult(count);
    setGenerating(false);
  };

  const handleCreateABTest = async () => {
    if (!abTestBundleId) return;
    const bundle = bundles.find((b) => b.id === abTestBundleId);
    if (!bundle) return;
    await createTest(fetch, {
      name: `${bundle.name} - Discount Test`,
      bundleId: abTestBundleId,
      variantDiscountPct: abTestVariantPct,
    });
    setAbTestBundleId(null);
    setAbTestVariantPct(10);
  };

  const autoGeneratedDrafts = bundles.filter(
    (b) => b.source === 'AUTO' && b.status === 'DRAFT',
  );
  const allBundles = bundles;

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '20px' }}>
      {/* Header */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: '20px',
        }}
      >
        <h1 style={{ fontSize: '24px', margin: 0 }}>Bundles</h1>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            onClick={handleGenerate}
            disabled={generating}
            style={{
              padding: '8px 16px',
              backgroundColor: '#ffffff',
              color: '#202223',
              border: '1px solid #c9cccf',
              borderRadius: '4px',
              cursor: generating ? 'not-allowed' : 'pointer',
              fontSize: '14px',
            }}
          >
            {generating ? 'Generating...' : 'Generate Bundles'}
          </button>
          <button
            onClick={() => navigate('/bundles/new')}
            style={{
              padding: '8px 16px',
              backgroundColor: '#008060',
              color: '#ffffff',
              border: 'none',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '14px',
              fontWeight: 600,
            }}
          >
            Create Bundle
          </button>
        </div>
      </div>

      {/* Generate result banner */}
      {generateResult !== null && (
        <div
          style={{
            padding: '12px 16px',
            backgroundColor: generateResult > 0 ? '#f1f8f5' : '#fff8e5',
            border: `1px solid ${generateResult > 0 ? '#aee9d1' : '#ffea8a'}`,
            borderRadius: '8px',
            marginBottom: '16px',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <span style={{ fontSize: '14px' }}>
            {generateResult > 0
              ? `${generateResult} bundle${generateResult !== 1 ? 's' : ''} generated as drafts. Review them below.`
              : 'No new bundles could be generated. Adjust your settings or add more products with COGS data.'}
          </span>
          <button
            onClick={() => setGenerateResult(null)}
            style={{
              background: 'none',
              border: 'none',
              cursor: 'pointer',
              fontSize: '16px',
              color: '#6d7175',
            }}
          >
            x
          </button>
        </div>
      )}

      {error && (
        <div
          style={{
            color: '#8c1a1a',
            padding: '12px',
            marginBottom: '12px',
            backgroundColor: '#ffd2d2',
            borderRadius: '8px',
          }}
        >
          Error: {error}
        </div>
      )}

      {loading ? (
        <LoadingState />
      ) : (
        <>
          {/* Auto-generated drafts section */}
          {autoGeneratedDrafts.length > 0 && (
            <div
              style={{
                marginBottom: '24px',
                border: '1px solid #e1e3e5',
                borderRadius: '8px',
                overflow: 'hidden',
              }}
            >
              <div
                style={{
                  padding: '12px 16px',
                  backgroundColor: '#fff8e5',
                  borderBottom: '1px solid #ffea8a',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <div>
                  <strong style={{ fontSize: '14px' }}>
                    Auto-Generated Bundles for Review
                  </strong>
                  <span
                    style={{
                      fontSize: '13px',
                      color: '#6d7175',
                      marginLeft: '8px',
                    }}
                  >
                    ({autoGeneratedDrafts.length} pending)
                  </span>
                </div>
              </div>
              <div style={{ padding: '0' }}>
                {autoGeneratedDrafts.map((bundle) => (
                  <div
                    key={bundle.id}
                    style={{
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      padding: '10px 16px',
                      borderBottom: '1px solid #f1f1f1',
                    }}
                  >
                    <div>
                      <div style={{ fontWeight: 500, fontSize: '14px' }}>
                        {bundle.name}
                      </div>
                      <div style={{ fontSize: '12px', color: '#6d7175' }}>
                        {bundle.items.length} items | $
                        {bundle.bundlePrice.toFixed(2)} | {bundle.discountPct}%
                        off
                        {bundle.contributionMarginPct !== null && (
                          <span
                            style={{
                              marginLeft: '8px',
                              color:
                                bundle.contributionMarginPct >= 15
                                  ? '#1a5632'
                                  : '#8c1a1a',
                            }}
                          >
                            Margin: {bundle.contributionMarginPct.toFixed(1)}%
                          </span>
                        )}
                      </div>
                    </div>
                    <div style={{ display: 'flex', gap: '6px' }}>
                      <button
                        onClick={() => handleStatusChange(bundle.id, 'ACTIVE')}
                        style={{
                          padding: '6px 14px',
                          backgroundColor: '#008060',
                          color: '#ffffff',
                          border: 'none',
                          borderRadius: '4px',
                          cursor: 'pointer',
                          fontSize: '13px',
                          fontWeight: 600,
                        }}
                      >
                        Approve
                      </button>
                      <button
                        onClick={() =>
                          handleStatusChange(bundle.id, 'ARCHIVED')
                        }
                        style={{
                          padding: '6px 14px',
                          backgroundColor: '#ffffff',
                          color: '#8c1a1a',
                          border: '1px solid #ffd2d2',
                          borderRadius: '4px',
                          cursor: 'pointer',
                          fontSize: '13px',
                        }}
                      >
                        Reject
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* All bundles table */}
          <div style={{ marginBottom: '8px' }}>
            <span style={{ fontSize: '13px', color: '#6d7175' }}>
              {allBundles.length} bundle{allBundles.length !== 1 ? 's' : ''}{' '}
              total
            </span>
          </div>
          <BundleTable
            bundles={allBundles}
            onEdit={handleEdit}
            onDelete={handleDelete}
            onStatusChange={handleStatusChange}
            onCreateABTest={(bundleId) => setAbTestBundleId(bundleId)}
          />
        </>
      )}

      {/* A/B Test creation dialog */}
      {abTestBundleId && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
          }}
        >
          <div
            style={{
              backgroundColor: '#ffffff',
              borderRadius: '12px',
              width: '480px',
              padding: '24px',
              boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
            }}
          >
            <h2 style={{ margin: '0 0 16px 0', fontSize: '18px' }}>
              Create A/B Test
            </h2>
            <div style={{ fontSize: '13px', color: '#6d7175', marginBottom: '16px' }}>
              Bundle: <strong style={{ color: '#202223' }}>
                {bundles.find((b) => b.id === abTestBundleId)?.name ?? abTestBundleId}
              </strong>
            </div>
            <div style={{ marginBottom: '16px' }}>
              <label style={{ display: 'block', fontSize: '13px', color: '#6d7175', marginBottom: '4px' }}>
                Variant Discount %
              </label>
              <input
                type="number"
                value={abTestVariantPct}
                onChange={(e) => setAbTestVariantPct(parseFloat(e.target.value) || 0)}
                min={1}
                max={100}
                step={1}
                style={{
                  width: '100%',
                  padding: '8px 12px',
                  border: '1px solid #c9cccf',
                  borderRadius: '4px',
                  fontSize: '14px',
                  boxSizing: 'border-box',
                }}
              />
              <div style={{ fontSize: '11px', color: '#6d7175', marginTop: '4px' }}>
                The control uses the current bundle discount. Set the variant discount to test against it.
              </div>
            </div>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px' }}>
              <button
                onClick={() => { setAbTestBundleId(null); setAbTestVariantPct(10); }}
                style={{
                  padding: '8px 16px',
                  backgroundColor: '#ffffff',
                  color: '#202223',
                  border: '1px solid #c9cccf',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontSize: '14px',
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleCreateABTest}
                style={{
                  padding: '8px 16px',
                  backgroundColor: '#008060',
                  color: '#ffffff',
                  border: 'none',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontSize: '14px',
                  fontWeight: 600,
                }}
              >
                Create Test
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
