-- AlterTable
ALTER TABLE `Bundle` ADD COLUMN `bogoGetDiscountPct` DECIMAL(5, 2) NULL,
    ADD COLUMN `bogoGetQuantity` INTEGER NULL,
    ADD COLUMN `countdownBgColor` VARCHAR(9) NOT NULL DEFAULT '#111827',
    ADD COLUMN `countdownDuration` INTEGER NULL,
    ADD COLUMN `countdownEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `countdownEndDate` DATETIME(3) NULL,
    ADD COLUMN `countdownTextColor` VARCHAR(9) NOT NULL DEFAULT '#ffffff',
    ADD COLUMN `countdownTitle` VARCHAR(255) NULL,
    ADD COLUMN `countdownType` VARCHAR(20) NOT NULL DEFAULT 'fixed',
    MODIFY `type` ENUM('FIXED', 'MIX_MATCH', 'VOLUME', 'CROSS_SELL', 'DEAD_STOCK', 'BOGO', 'COLLECTION') NOT NULL;

-- AlterTable
ALTER TABLE `ShopSettings` ADD COLUMN `widgetBadgeFontSize` INTEGER NOT NULL DEFAULT 12,
    ADD COLUMN `widgetBadgeFontWeight` VARCHAR(10) NOT NULL DEFAULT 'bold',
    ADD COLUMN `widgetBlockTitleColor` VARCHAR(9) NOT NULL DEFAULT '#111827',
    ADD COLUMN `widgetBlockTitleFontSize` INTEGER NOT NULL DEFAULT 18,
    ADD COLUMN `widgetBlockTitleFontWeight` VARCHAR(10) NOT NULL DEFAULT 'bold',
    ADD COLUMN `widgetButtonFontSize` INTEGER NOT NULL DEFAULT 14,
    ADD COLUMN `widgetButtonFontWeight` VARCHAR(10) NOT NULL DEFAULT 'bold',
    ADD COLUMN `widgetButtonTextColor` VARCHAR(9) NOT NULL DEFAULT '#ffffff',
    ADD COLUMN `widgetCardHoverBgColor` VARCHAR(9) NOT NULL DEFAULT '#f9fafb',
    ADD COLUMN `widgetItemTitleFontSize` INTEGER NOT NULL DEFAULT 14,
    ADD COLUMN `widgetItemTitleFontWeight` VARCHAR(10) NOT NULL DEFAULT 'normal',
    ADD COLUMN `widgetLabelBgColor` VARCHAR(9) NOT NULL DEFAULT '#e0e7ff',
    ADD COLUMN `widgetLabelTextColor` VARCHAR(9) NOT NULL DEFAULT '#3730a3',
    ADD COLUMN `widgetOriginalPriceColor` VARCHAR(9) NOT NULL DEFAULT '#9ca3af',
    ADD COLUMN `widgetPriceColor` VARCHAR(9) NOT NULL DEFAULT '#111827',
    ADD COLUMN `widgetPriceFontSize` INTEGER NOT NULL DEFAULT 16,
    ADD COLUMN `widgetPriceFontWeight` VARCHAR(10) NOT NULL DEFAULT 'bold',
    ADD COLUMN `widgetSavingsBadgeBgColor` VARCHAR(9) NOT NULL DEFAULT '#dcfce7',
    ADD COLUMN `widgetSavingsBadgeTextColor` VARCHAR(9) NOT NULL DEFAULT '#166534',
    ADD COLUMN `widgetSelectedBgColor` VARCHAR(9) NOT NULL DEFAULT '#eff6ff',
    ADD COLUMN `widgetSubtitleColor` VARCHAR(9) NOT NULL DEFAULT '#6b7280',
    ADD COLUMN `widgetSubtitleFontSize` INTEGER NOT NULL DEFAULT 13,
    ADD COLUMN `widgetSubtitleFontWeight` VARCHAR(10) NOT NULL DEFAULT 'normal',
    ADD COLUMN `widgetTitleColor` VARCHAR(9) NOT NULL DEFAULT '#111827';
